<?php

namespace PatientBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AppointmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentRepository extends EntityRepository
{
    public function getDay($year, $month, $day)
    {
        $q = $this->createQueryBuilder('v');

        $q->select('v')
            ->where('v.year = :year', 'v.month = :month', 'v.day = :day')
            ->setParameter('year', $year)
            ->setParameter('month', $month)
            ->setParameter('day', $day)
        ;

        return $q->getQuery()->getResult();
    }

    public function findVisitsByMonth($year, $month, $day)
    {
        $visits = $this->getEntityManager()->createQuery(
            'Select p from PatientBundle:Appointment p WHERE p.year LIKE :year AND p.month LIKE :month AND p.day LIKE :day ORDER BY p.hour')
            ->setParameter('year', $year)
            ->setParameter('month', $month)
            ->setParameter('day', $day)
            ->getResult();

        return $visits;
    }

    public function getVisitsByMonth($year, $month, $day)
    {
        $q = $this->createQueryBuilder('v');

        $q->select('v')
            ->where('v.year = :year', 'v.month = :month', 'v.day = :day')
            ->setParameter('year', $year)
            ->setParameter('month', $month)
            ->setParameter('day', $day)
            ->orderBy('v.hour', 'ASC');
        ;

        return $q->getQuery()->getResult();
    }

    public function findVisits($year, $month)
    {
        $visits = $this->getEntityManager()->createQuery(
            'Select p from PatientBundle:Appointment p WHERE p.year LIKE :year AND p.month LIKE :month ORDER BY p.day')
            ->setParameter('year', $year)
            ->setParameter('month', $month)
            ->getResult();

        return $visits;
    }

    public function getVisitByHour($year, $month, $day, $hour)
    {
        $q = $this->createQueryBuilder('m');

        $q->select('m')
            ->where('m.year = :year', 'm.month = :month', 'm.day = :day', 'm.hour = :hour')
            ->setParameter('year', $year)
            ->setParameter('month', $month)
            ->setParameter('day', $day)
            ->setParameter('hour', $hour)
        ;

        return $q->getQuery()->getSingleResult();
    }
}
