<?php

namespace PatientBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AppointmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentRepository extends EntityRepository
{
    public function findDay($year, $month, $day)
    {
//        $dino = $this->getEntityManager()->createQuery(
//            'SELECT p from DinoCompareBundle:DinoData p WHERE p.name LIKE :text')
//            ->setParameter('text', '%' . $text . '%')
//            ->getResult();
//
//        return $dino;

        $daySchedule = $this->getEntityManager()->createQuery(
            'Select p from PatientBundle:Appointment p WHERE p.year LIKE :year AND p.month LIKE :month AND p.day LIKE :day')
            ->setParameter('year', $year)
            ->setParameter('month', $month)
            ->setParameter('day', $day)
            ->getResult();

        return $daySchedule;
    }
}
