<?php

namespace PatientBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlockDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockDayRepository extends EntityRepository
{
    public function findDay($year, $month, $day)
    {
        $daySchedule = $this->getEntityManager()->createQuery(
            'Select p from PatientBundle:BlockDay p WHERE p.year LIKE :year AND p.month LIKE :month AND p.day LIKE :day')
            ->setParameter('year', $year)
            ->setParameter('month', $month)
            ->setParameter('day', $day)
            ->getResult();

        return $daySchedule;
    }
}
